In [279]:
import numpy as np
import matplotlib.pyplot as plt

In [280]:
data = np.genfromtxt(r"C:/Users/bit.LAB4-11/Downloads/regression_data.csv",delimiter = ",", dtype = "int")

In [281]:
data = data[1:,:]
print(data)

[[   1 2272]
 [   3 1386]
 [   4 1365]
 ..., 
 [ 741 5392]
 [ 742 5906]
 [ 743 4881]]


In [282]:
n = data.shape[0]
x = data[:,0].reshape((n,1))
X = x
y = data[:,1].reshape((n,1))
Y = y

In [283]:
meanx = np.mean(x,axis = 0)
stdx = np.std(x,axis = 0)
varx = stdx*stdx

In [284]:
meany = np.mean(y,axis = 0)
stdy = np.std(y,axis = 0)
vary = stdy*stdy

In [285]:
x = (x - np.tile(meanx,(n,1))) / np.tile(stdx,(n,1))

In [286]:
y = (y - np.tile(meany,(n,1))) / np.tile(stdy,(n,1))

In [287]:
plt.scatter(x,y)

In [288]:
plt.show()

In [300]:
karl_coeff = np.sum((X - np.tile(meanx,(n,1)))*(Y - np.tile(meany,(n,1))))/(n * varx * vary)
karl_coeff

array([  3.50916115e-06])

In [301]:
cov = karl_coeff * varx * vary
cov

array([ 118639.09149706])

In [291]:
randperm = np.random.RandomState(seed=98).permutation(np.shape(x)[0])

In [292]:
x_rand = np.array([x[i] for i in randperm])

In [293]:
y_rand = np.array([y[i] for i in randperm])

In [294]:
upto = int(0.75 * np.shape(x_rand)[0])
trainx = x_rand[:upto,:]
trainy = y_rand[:upto,:]
testx = x_rand[upto:,:]
testy = y_rand[upto:,:]

In [302]:
w1 = (np.mean(trainx*trainy) - np.mean(trainx)*np.mean(trainy))/(np.mean(trainx*trainx) - np.mean(trainx)*np.mean(trainx))
w1

0.61606462179260835

In [296]:
w0 = np.mean(trainy) - w1*np.mean(trainx)
w0

-0.017742131396625907

In [303]:
xplot = np.linspace(np.min(trainx),np.max(trainx),300)
yplot = [w0 + w1*xplot]

In [304]:
plt.scatter(xplot,yplot,alpha = 0.5, linewidth = 0.01, c = 'green')
plt.scatter(x,y,alpha = 0.3)

In [ ]:
plt.show()

In [273]:
X2 = X*X
X3 = X*X*X
X = np.hstack((X,X2))
X = np.hstack((X,X3))

In [278]:
cov

array([ 118639.09149706])